# Generated by Django 5.1.2 on 2024-10-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('flat', 'Flat Discount'), ('percentage', 'Percentage Discount')], default='flat', max_length=10),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expiry_date',
            field=models.DateField(),
        ),
    ]
