# Generated by Django 5.1.2 on 2024-10-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_reward_points', models.PositiveIntegerField(default=10, help_text='Points awarded per referral')),
                ('point_to_cash_conversion_rate', models.DecimalField(decimal_places=2, default=1.0, help_text='Conversion rate from points to wallet cash', max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='AppSettings',
        ),
    ]
