# Generated by Django 5.1.2 on 2024-10-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_conversions_delete_appsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_banner', models.ImageField(blank=True, help_text='Primary offer banner', null=True, upload_to='banners/offer/')),
                ('banner', models.ImageField(blank=True, help_text='Main banner', null=True, upload_to='banners/main/')),
                ('secondary_banner', models.ImageField(blank=True, help_text='Secondary banner', null=True, upload_to='banners/secondary/')),
            ],
        ),
    ]
