# Generated by Django 5.1.2 on 2024-10-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_banners'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_type', models.IntegerField(choices=[(1, 'Offer Banner'), (2, 'Main Banner'), (3, 'Secondary Banner')], help_text='Type of banner')),
                ('image', models.ImageField(blank=True, help_text='Image for the banner', null=True, upload_to='banners/images/')),
                ('redirect_url', models.URLField(blank=True, help_text='Optional URL to redirect when banner is clicked', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Banners',
        ),
    ]
