# Generated by Django 5.1.2 on 2024-10-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_banner_delete_banners'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_enabled', models.BooleanField(default=True, help_text='Enable Cash on Delivery')),
                ('wallet_enabled', models.BooleanField(default=True, help_text='Enable payment via Wallet Balance')),
                ('razorpay_enabled', models.BooleanField(default=True, help_text='Enable Razorpay Payment Gateway')),
            ],
        ),
    ]
