# Generated by Django 5.1.2 on 2024-10-22 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_prescription_order'),
    ]

    operations = [
    ]
