# Generated by Django 5.1.2 on 2024-10-22 17:35

from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0003_auto_20241022_1734'),
    ]

    operations = [
    ]
