# Generated by Django 5.1.2 on 2024-10-22 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0004_auto_20241022_1735'),
        ('products', '0005_remove_product_attributes_productattribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='order',
        ),
        migrations.AddField(
            model_name='prescription',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='prescription',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
