# Generated by Django 5.1.2 on 2024-10-22 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0005_remove_prescription_order_and_more'),
        ('products', '0005_remove_product_attributes_productattribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.CreateModel(
            name='PrescriptionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('Wallet', 'Wallet'), ('Razorpay', 'Razorpay')], max_length=20, null=True)),
                ('prescription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='prescriptions.prescription')),
            ],
        ),
    ]
