# Generated by Django 5.1.2 on 2024-10-22 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0008_alter_prescriptionorder_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionorder',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
