# Generated by Django 5.1.2 on 2024-10-25 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_coupon_discount_type_alter_coupon_expiry_date'),
        ('prescriptions', '0010_alter_prescription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionorder',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupons.coupon'),
        ),
    ]
