# Generated by Django 5.1.2 on 2024-10-19 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_payment_method_payment'),
        ('products', '0005_remove_product_attributes_productattribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='selected_attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productattribute'),
        ),
    ]
