# Generated by Django 5.1.2 on 2024-10-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_image_file_notification_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='image_url',
        ),
        migrations.AddField(
            model_name='notification',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='notification_images/'),
        ),
    ]
